name: fitness_tracker
description: A fitness tracking app that monitors workouts, steps, and calories burned with goal setting, progress tracking, and wearable integration.

# The version of your application
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Updated to support Dart null safety

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.4
  firebase_auth_web: ^5.9.4
  firebase_core: ^2.25.4
  firebase_core_web: ^2.11.4
  validators: 3.0.0

  cloud_firestore: ^4.11.0
  provider: ^6.0.5
  flutter_local_notifications: ^9.0.0
  google_sign_in: ^5.4.2
  charts_flutter: ^0.12.0
  intl: 0.17.0
  fluttertoast: ^8.0.9
  pedometer: ^4.0.2
  intl_phone_number_input: 0.7.4
  geolocator: ^9.0.2
  libphonenumber: ^2.0.2
  mailer: ^6.2.0
  firebase_messaging: ^14.9.4
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0           # Linting for best practices

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/packages/intl_phone_number_input/assets/flags/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic



# Additional configurations for iOS and Android permissions
# Add platform-specific permission settings in your AndroidManifest.xml and Info.plist as required.
